// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAdklLF0ZdPFR3PtPmjMvEX27BjOtQv-4w',
    appId: '1:802865466863:web:a16fdb01f802c47d29fa1a',
    messagingSenderId: '802865466863',
    projectId: 'smart-trip-ai-19f3f',
    authDomain: 'smart-trip-ai-19f3f.firebaseapp.com',
    storageBucket: 'smart-trip-ai-19f3f.firebasestorage.app',
    measurementId: 'G-30KHYF27WZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCLnTvpJq-FHB5v0dHP3VNypqAhpwNXGvs',
    appId: '1:802865466863:android:2d69609b516d429c29fa1a',
    messagingSenderId: '802865466863',
    projectId: 'smart-trip-ai-19f3f',
    storageBucket: 'smart-trip-ai-19f3f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAX1LzAcUWKSFa8y86lQYfQHH6wINgl0qY',
    appId: '1:802865466863:ios:f533e4c84788497a29fa1a',
    messagingSenderId: '802865466863',
    projectId: 'smart-trip-ai-19f3f',
    storageBucket: 'smart-trip-ai-19f3f.firebasestorage.app',
    iosBundleId: 'com.example.smarttripAi',
  );
}
